apiVersion: v1
kind: Service
metadata:
  name: cronjob
  namespace: citrusops
spec:
  selector:
    app: cronjob
  ports:
    - port: 50059
      targetPort: 50059
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cronjob
  namespace: citrusops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cronjob
  template:
    metadata:
      labels:
        app: cronjob
    spec:
      containers:
        - name: cronjob
          image: mraza176/citrusops-cronjob:v2
          imagePullPolicy: IfNotPresent
          env:
            - name: MONGO_URL
              value: "mongodb://mongouser:mongopassword@mongo.citrusops.svc.cluster.local:27017/admin?authSource=admin"
            - name: REDIS_URL
              value: "redis.citrusops.svc.cluster.local:6379"
            - name: NOTIFICATION_SERVICE_URL
              value: "notification.citrusops.svc.cluster.local:50055"
            - name: ARGOCD_TOKEN
              value: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhcmdvY2QiLCJzdWIiOiJhZGlsMTphcGlLZXkiLCJuYmYiOjE3NjQwNjIxMzUsImlhdCI6MTc2NDA2MjEzNSwianRpIjoiYzc2ZWUyMmQtYzZlYS00NjQ3LWI0Y2ItZWYyOWRjM2FjMjAxIn0.icxgt-WwZBkKNMZSaY5_vTeUeT2-71MZkf_u69lphzI"
